services:
  front:
    image: projet_front
    build: ./front
    hostname: projet_front
    container_name: project_front
    ports:
      - "80:4200"
    environment:
      - API_URL=project_back
    networks:
      - project

  back:
    image: project_back
    build: ./back
    hostname: project_back
    container_name: project_back
    ports: 
      - "3000:3000"
    volumes:
      - project_back_plugins:/usr/src/app/plugins
    environment:
      MONGO_URL: mongodb://project_db:27017/admin
    networks:
      - project
  
  mongo:
    image: mongo
    hostname: project_db
    volumes:
      - project_db_data:/data/db
    networks:
      - project

volumes:
  project_back_plugins:
  project_db_data:

networks:
  project: {}
